import { Inter } from "next/font/google";
import "./globals.css";
import { lazy, Suspense } from "react";
import StoreProvider from "@/redux/StoreProvider";
const Navbar = lazy(() => import("@/components/custom/Navbar"));
const Footer = lazy(() => import("@/components/custom/Footer"));
const Background = lazy(() => import("@/components/custom/Background"));

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Befog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Suspense fallback={null}>
          <StoreProvider>
            <>
              <span id="back-top-top" className="absolute top-0" />
              <Background />
              <Navbar />
              <main className="text-white mt-[4.5rem] flex-grow">
                {children}
              </main>
              <Footer />
            </>
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
